---
kind: pipeline
type: docker
name: Install Step CA Server

clone:
  depth: 1

steps:

  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/production/hosts
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password 

trigger:
  branch:
    - development
  event:
    - push
...
