# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: all
  roles:
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - name: 'Render ca.json.j2 to {{ config_dir }}/config/ca.json'
      template:
        src: ca.json.j2
        dest: '{{ config_dir }}/config/ca.json'

    - name: 'Render defaults.json.j2 to {{ config_dir }}/config/defaults.json'
      template:
        src: defaults.json.j2
        dest: '{{ config_dir }}/config/defaults.json'

    - include_role:
        name: docker
        tasks_from: stack_deploy
