# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: all
  roles:
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - name: 'Ensure {{ config_dir }}/config/ exists'
      file:
        state: directory
        path: '{{ config_dir }}/config'

    - name: 'Ensure {{ config_dir }}/secrets/ exists'
      file:
        state: directory
        path: '{{ config_dir }}/secrets'

    - name: 'Render password.j2 to {{ config_dir }}/secrets/password'
      template:
        src: password.j2
        dest: '{{ config_dir }}/secrets/password'

    - name: 'Render ca.json.j2 to {{ config_dir }}/config/ca.json'
      template:
        src: ca.json.j2
        dest: '{{ config_dir }}/config/ca.json'

    - name: 'Render defaults.json.j2 to {{ config_dir }}/config/defaults.json'
      template:
        src: defaults.json.j2
        dest: '{{ config_dir }}/config/defaults.json'

    - include_role:
        name: docker
        tasks_from: stack_deploy
